{{- $services := (include "buildsphere.backendServices" . | fromYaml).services -}}
{{- range $service := $services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "buildsphere.componentName" (dict "root" $ "component" $service.name) }}
  labels:
    {{- include "buildsphere.commonLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $service.name }}
automountServiceAccountToken: false
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "buildsphere.componentName" (dict "root" . "component" "frontend") }}
  labels:
    {{- include "buildsphere.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "buildsphere.componentName" (dict "root" . "component" "migration") }}
  labels:
    {{- include "buildsphere.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "buildsphere.componentName" (dict "root" . "component" "chart-test") }}
  labels:
    {{- include "buildsphere.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: chart-test
automountServiceAccountToken: false
