global:
  scrape_interval: 15s

scrape_configs:
  - job_name: buildsphere-services
    static_configs:
      - targets:
          - api-gateway:8080
          - auth-service:8081
          - project-service:8082
