{{- include "buildsphere-personal-prerequisites.validate" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "buildsphere-personal-prerequisites.fullname" . }}
  labels:
    {{- include "buildsphere-personal-prerequisites.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
automountServiceAccountToken: false
